
# name of the workflow pipeline
name: github action demo pipeline
# trigger event
on:
  push:
      branches:
         - main
jobs:
  demo-job:
      runs-on: ubuntu-latest

      steps:
         -name: checkout code
         uses: action/checkout@v2
         -name: print message
         runs: echo "welcome to github actions"